# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedBullApp', '0003_auto_20180715_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=2318814890, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='referall',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
